import { use } from 'react';
import { Inter } from '@next/font/google';
import '../styles/styles.min.css';
import Header from 'components/header';
import ApolloProvider from 'modules/apolloClient';
import AppProvider from 'modules/appContext';
import UIProvider from 'ui/context';
import CurrentUser from 'modules/auth/currentUser';
import choosePos from 'lib/choosePos';
import 'react-toastify/dist/ReactToastify.min.css';
import Toast from 'ui/Toast';
import CurrentOrder from 'modules/checkout/currentOrder';
import Footer from 'components/footer';

const Font = Inter({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // use(choosePos());
  return (
    <html lang="en" className={Font.className}>
      <head>
        <title>Techstore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ApolloProvider>
          <AppProvider>
            <UIProvider>
              <Header />
              <div className="min-height-screen">
                <CurrentUser>
                  <CurrentOrder>{children}</CurrentOrder>
                </CurrentUser>
              </div>
              <Footer />
            </UIProvider>
          </AppProvider>
        </ApolloProvider>
        <Toast />
      </body>
    </html>
  );
}
