import { use } from 'react';
import { Inter } from '@next/font/google';
import '../styles/styles.min.css';
import Header from 'components/header';
import Provider from 'modules/apolloClient';
import AppProvider from 'modules/appContext';
import UIProvider from 'ui/context';
import CurrentUser from 'modules/auth/currentUser';
import choosePos from 'lib/choosePos';

const Font = Inter({
  subsets: ['latin', 'cyrillic'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  use(choosePos());
  return (
    <html lang="en" className={Font.className}>
      <head>
        <title>Techstore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Provider>
          <AppProvider>
            <UIProvider>
              <CurrentUser>
                <Header />
                {children}
              </CurrentUser>
            </UIProvider>
          </AppProvider>
        </Provider>
      </body>
    </html>
  );
}
